### ISSUE TITLE
Application crashes when connecting with Safari

### ISSUE THREAD

**Issue by birme** [Eyevinn/srt-whep#27] opened 2023-07-04 11:46 UTC
```
0:01:51.712577629     1 0x7fec68015640 ERROR              webrtcice gstwebrtcice.c:316:_resolve_host: Error resolving “a64f400a-abbf-481e-8ee6-3676dfb9c509.local”: Name or service not known
0:01:51.713538447     1 0x7fec68015640 ERROR              webrtcice gstwebrtcice.c:316:_resolve_host: Error resolving “a64f400a-abbf-481e-8ee6-3676dfb9c509.local”: Name or service not known
**
ERROR:../ext/webrtc/gstwebrtcbin.c:2304:sdp_media_from_transceiver: assertion failed: (trans->mline == -1 || trans->mline == media_idx)
```

**Comment by Wkkkkk** [comment] 2023-07-06 20:37
Hi @birme , I found that Safari prefers h264 of profile `constrained-baseline`.
To verify that, we could generate a local test stream. 
```
gst-launch-1.0 -v \
    videotestsrc ! clockoverlay ! video/x-raw, height=360, width=640 ! videoconvert ! x264enc tune=zerolatency ! video/x-h264, profile=constrained-baseline ! mux. \
    audiotestsrc ! audio/x-raw, format=S16LE, channels=2, rate=44100 ! audioconvert ! voaacenc ! aacparse ! mux. \
    mpegtsmux name=mux ! queue ! srtsink uri="srt://127.0.0.1:1234?mode=listener" wait-for-connection=false
```

And then
```
GST_DEBUG=1 cargo run --release -- -i 127.0.0.1:1234 -o 127.0.0.1:8888 -p 8000 -s caller | bunyan
```

**Comment by Wkkkkk** [comment] 2023-07-06 20:43
Here is a screenshot of it running.
<img width="1127" alt="Screenshot 2023-07-06 at 22 42 14" src="https://github.com/Eyevinn/srt-whep/assets/15907534/686e85c7-bd54-430d-b210-17ddfe992fb4">

**Comment by birme** [comment] 2023-07-06 20:46
Ah, that's good to know.
Still the main issue now is the #32 which I think happens every time the app tries to remove a client connection.

**Comment by Wkkkkk** [comment] 2023-07-06 20:49
That's true. We still need to fix that.

**Comment by Wkkkkk** [comment] 2023-08-07 14:35
Some updates on this issue:
- This problem occurs when we connect to an SRT stream with `main` or `high` H264 video profile. Media line exists in the answer but is not included in BUNDLE and ice candidates exchange will time out (similar to issue #26).
- One possible workaround for H264 video is to transcode the stream into a supported profile before connection (as in issue #36). However, this is not recommended as it is computing expensive and it is not possible for H265 video on Mac.
- A better fix is to look into the answer generated by browsers and understand the cause for missing media lines.

**Comment by birme** [comment] 2023-08-07 14:38
Also, one rationale not to transcode the video stream in this component is that we want to maintain the video as it is as one use case is confidence monitoring or preview. It is ok for now to limit supported browsers depending on the actual SRT video stream. However the component should not crash or end up in an unresolvable state.

**Comment by Wkkkkk** [comment] 2023-08-17 20:27
This has been addressed in the recent [commit](https://github.com/Eyevinn/srt-whep/commit/ded88083898c0b1d5bcefdc0299c0bd20af3230f) so this becomes less of a issue now.

However, it is still a problem that Safari rejects `AVC/H264` streams of `main` or `high` profile. This relates to how Safari parses the codecs parameters (e.g., profile-level-id) and more test will be done.

**Comment by birme** [comment] 2023-08-17 21:32
Alright, good to know.
We should perhaps document all the known limitations somewhere?

**Comment by Wkkkkk** [comment] 2023-08-18 15:47
While experimenting with Safari and `AVC/H264` streams, it is noticed that Safari only supports WebRTC H264 of `constrained-baseline` and `constrained-high` profiles. This can be seen from the SDP offer it generated (either with webrtc player in client mode or with other tools like [MungeSDP](https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/)).

> a=rtpmap:96 H264/90000
...
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:98 H264/90000
...
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

Here profile-level-id can be parsed into `constrained high level 3.1` and `constrained baseline level 3.1` respectively, as it is [defined](https://github.com/webrtc-uwp/webrtc/blob/d1b53b61fb41a3aec58668f07e230f0b54560029/sdk/objc/components/video_codec/RTCH264ProfileLevelId.mm#L30C28-L30C43) in the WebRTC repository. Unfortunately, neither ffmpeg nor gstreamer could generate video streams of `constrained high` profile. So we instead tested with one stream of `constrained baseline` and one of `high` (munging the profile-level-id from '64001e' to '640c1f' in SDP offer).

As we have seen before, `constrained baseline` video stream can be played out successfully on Safari. On the other hand,  `high` video stream will be rejected. But if we munge it into '640c1f', the connection can be established but no stream is actually played out.

With the findings so far, a document about these limitations will be drafted and included in this repo soon.

**Closed** 2023-08-18 15:47 UTC
Labels: bug
